name: Glitch Sync

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Sync to Glitch Project
      uses: kanadgupta/glitch-sync@main
      with:
        project-id: '${{ secrets.PROJECT_ID }}'
        auth-token: '${{ secrets.AUTH_TOKEN }}'
